### PR TITLE
Fix python3 import error

### PR DESCRIPTION
**Pull request by r9y9**
```
 File "/home/ryuichi/Dropbox/sp/merlin_pr/src/utils/file_paths.py",
 line 22, in <module>
     from utils import prepare_file_path_list
     ImportError: cannot import name 'prepare_file_path_list'
```

This is because there are two `utils` modules in merlin, src/utils
and src/utils/utils. Fixing this by explicitly importing the module
we need.

Seems to be caused by #220.

EDIT: The above error happened when I tried to run `slt_arctic` demo.

### CODE REVIEW

**Comment by r9y9** [comment]
By the way, it would be great to have unit-testing infrastructure to avoid introducing a new bug when adding features, fixing bugs, etc.

**Comment by ronanki** [comment]
@r9y9 We're also thinking about this -- but never got time to do. Happy to accept as a PR.
